### ISSUE TITLE
Training error while running faster_rcnn/train_net.py

### ISSUE THREAD

**Issue by aditipanda** [Zardinality/TF_Deformable_Net#27]
I was running the following command: 
python faster_rcnn/train_net.py --gpu 0 --weights ./data/pretrain_mod
el/Resnet50.npy --imdb voc_2007_trainval --iters 70000 --cfg  ./experiments/cfgs/faster_rcnn_end2end_resnet.yml --network Resnet50_train --set EXP_DIR exp_dir

when I got this error:
 **File "faster_rcnn/train_net.py", line 29, in <module>
    from lib.datasets.factory import get_imdb
  File "/home/aditi/Documents/PhD/Steel_Seg/Deformable-ConvNets/TF_Deformable_Net-master/lib/datasets/__init__.py", line 13, in <module>
    from .imagenet3d import imagenet3d
  File "/home/aditi/Documents/PhD/Steel_Seg/Deformable-ConvNets/TF_Deformable_Net-master/lib/datasets/imagenet3d.py", line 1, in <module>
    from . import imagenet3d
ImportError: cannot import name imagenet3d**

in lib folder, make runs fine with a few warnings.

**Comment by aditipanda** [comment]
Also while trying to run the demo with the command: _python faster_rcnn/demo.py --model ~/tf_deformable_net/restore_output/Resnet50_iter_145000.ckpt_, I get this error:

**Traceback (most recent call last):
  File "faster_rcnn/demo.py", line 21, in <module>
    from lib.networks.factory import get_network
  File "/home/aditi/Documents/PhD/Steel_Seg/Deformable-ConvNets/TF_Deformable_Net-master/lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/aditi/Documents/PhD/Steel_Seg/Deformable-ConvNets/TF_Deformable_Net-master/lib/networks/VGGnet_train.py", line 2, in <module>
    from .network import Network
  File "/home/aditi/Documents/PhD/Steel_Seg/Deformable-ConvNets/TF_Deformable_Net-master/lib/networks/network.py", line 11, in <module>
    from ..psroi_pooling_layer import psroi_pooling_op as psroi_pooling_op
  File "/home/aditi/Documents/PhD/Steel_Seg/Deformable-ConvNets/TF_Deformable_Net-master/lib/psroi_pooling_layer/psroi_pooling_op.py", line 5, in <module>
    _psroi_pooling_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/aditi/Documents/PhD/Steel_Seg/Deformable-ConvNets/TF_Deformable_Net-master/lib/psroi_pooling_layer/psroi_pooling.so: undefined symbol: _ZTIN10tensorflow8OpKernelE**

**Comment by BboyHanat** [comment]
add this flag to g++ complie part in the make.sh file:
 -L $TF_LIB -ltensorflow_framework
